### ISSUE TITLE
Please Provide a License information for this library 

### ISSUE THREAD

**Issue by atapas** [ilyakharlamov/pure-xsl#1]
Hello,

We liked the cool work you have done here. However we are not sure what is the License term for using it.

With your another work it is clearly mentioned that, that is under MIT license(https://github.com/ilyakharlamov/xslt_base64#contact).

Could you please clarify the same for this library as well? I would be looking for a similar MIT kind of open source license for my consumption before using the alternatives.

Thanks,
-Tapas

**Comment by ilyakharlamov** [comment]
Added MIT license #2
